export const CTR_PER_PAGE = 9

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"

export const GET_COUNTRIES_BY_CONTINENT_ORDER_NAME = "GET_COUNTRIES_BY_CONTINENT_ORDER_NAME"

export const CREATE_ACTIVITY = "CREATE_ACTIVITY"

export const GET_COUNTRIES_BY_CONTINENT_ORDER_POPULATION = "GET_COUNTRIES_BY_CONTINENT_ORDER_POPULATION"
